# Word Embedding Techniques using Embedding Layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
### Vocabulary size
voc_size=10000

One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2169, 9176, 9314, 5714], [2169, 9176, 9314, 5795], [2169, 8161, 9314, 9778], [3862, 6832, 9347, 3077, 9985], [3862, 6832, 9347, 3077, 7372], [5847, 2169, 1132, 9314, 6636], [1001, 5282, 3132, 3077]]


In [6]:
#Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
sent_length=8
dim=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2169 9176 9314 5714]
 [   0    0    0    0 2169 9176 9314 5795]
 [   0    0    0    0 2169 8161 9314 9778]
 [   0    0    0 3862 6832 9347 3077 9985]
 [   0    0    0 3862 6832 9347 3077 7372]
 [   0    0    0 5847 2169 1132 9314 6636]
 [   0    0    0    0 1001 5282 3132 3077]]


In [7]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()
print(model.predict(embedded_docs))

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________
[[[ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451
    0.04162848 -0.04395813 -0.02201762  0.0148901   0.04331442]
  [ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451
    0.04162848 -0.04395813 -0.02201762  0.0148901   0.04331442]
  [ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451
    0.04162848 -0.04395813 -0.02201762  0.0148901   0.04331442]
  [ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451
    0.04162848 -0.04395813 -0.02201762  0.0148901   0.04331442]
  [-0.03750076 -0.02809014  0.03333331 -0.04011625 -0.0220222
   -0.00613226 -0.0055481  -0.01625923 -0.01691662 -0.01942664]
  [ 0.0362

In [8]:
embedded_docs[0]

array([   0,    0,    0,    0, 2169, 9176, 9314, 5714])

In [9]:
print(model.predict(embedded_docs)[0])

[[ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451  0.04162848
  -0.04395813 -0.02201762  0.0148901   0.04331442]
 [ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451  0.04162848
  -0.04395813 -0.02201762  0.0148901   0.04331442]
 [ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451  0.04162848
  -0.04395813 -0.02201762  0.0148901   0.04331442]
 [ 0.01245194 -0.04098321  0.03448294 -0.02847089 -0.02270451  0.04162848
  -0.04395813 -0.02201762  0.0148901   0.04331442]
 [-0.03750076 -0.02809014  0.03333331 -0.04011625 -0.0220222  -0.00613226
  -0.0055481  -0.01625923 -0.01691662 -0.01942664]
 [ 0.03628879 -0.0364543  -0.00617323 -0.02087389  0.04342714  0.00033439
  -0.03588458  0.01293429  0.00687518  0.03040891]
 [-0.00831591 -0.01041645  0.00460757 -0.04343445  0.0114692   0.04230363
   0.02573794 -0.0214873  -0.01420858  0.03407141]
 [ 0.02874819 -0.02379694  0.01462321 -0.00991653  0.02734653  0.04585114
   0.03958248 -0.02577682  0.00817614  0.04032264]]