In [2]:
import numpy as np
Input=list(map(int,input().split()))
M_A=[]
M_B=[]
for i in range(Input[0]):
    A=np.array(list(map(int,input().split())))
    M_A.append(A)
for i in range(Input[0]):
    B=np.array(list(map(int,input().split())))
    M_B.append(B)
print(np.add(M_A,M_B))
print(np.subtract(M_A,M_B))
print(np.multiply(M_A,M_B))
print(np.divide(M_A,M_B).astype(int))
print(np.mod(M_A,M_B))
print(np.power(M_A,M_B))

2 4
1 2 3 4
1 2 3 4
5 6 7 7
5 6 7 7
[[ 6  8 10 11]
 [ 6  8 10 11]]
[[-4 -4 -4 -3]
 [-4 -4 -4 -3]]
[[ 5 12 21 28]
 [ 5 12 21 28]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [1 2 3 4]]
[[    1    64  2187 16384]
 [    1    64  2187 16384]]


In [ ]:
#INPUT
#2 4
#1 2 3 4
#1 2 3 4
#5 6 7 7
#5 6 7 7

#Output:

#[[ 6  8 10 11]
#[ 6  8 10 11]]
#[[-4 -4 -4 -3]
# [-4 -4 -4 -3]]
#[[ 5 12 21 28]
# [ 5 12 21 28]]
#[[0 0 0 0]
# [0 0 0 0]]
#[[1 2 3 4]
# [1 2 3 4]]
#[[    1    64  2187 16384]
# [    1    64  2187 16384]]