In [5]:
import numpy as np
Input=list(map(float,input().split()))
Array=np.array(Input)
np.set_printoptions(legacy='1.13')
print((np.floor(Array)))
print(format(np.ceil(Array)))
print(format(np.rint(Array)))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
