In [1]:
import numpy as np
np.set_printoptions(legacy='1.13')
Input=list(map(int,input().split()))
List_zeros=np.zeros(Input,dtype='int')
List_ones=np.ones(Input,dtype='int')
print(List_zeros)
print(List_ones)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
